// This file is auto-generated by vite-icons-type-plugin.
export type IconName =
	| "arrow-left-right"
	| "arrow-right-left"
	| "banknote"
	| "chart-area"
	| "check"
	| "chevron-left"
	| "chevron-right"
	| "chevrons-up-down"
	| "hledger"
	| "info"
	| "list"
	| "no-icon"
	| "refresh-cw"
	| "settings"
	| "wallet";
